### ISSUE TITLE
技術質問　2024/11/10

### ISSUE THREAD

**Issue by katou-kaede** [katou-kaede/portfolio#99]
## 解決したいこと・達成したいものについて
GitHubActionを使ったCIの設定

## 聞きたいこと・アドバイスが欲しいこと
`GitHubActionを使ったCIの設定(RSpecを追加予定だと思いますのでminitestから移行してください)`と教えていただいたのですが、具体的にどうなったらISSUEを完了にしていいのかがよくわかりません。
元から.gitthub/workflows/ci.ymlというファイルが存在していたのですが、そこのテストの部分を修正できれば完了という認識でいいのでしょうか。

## 実装の際に参考にした資料等
https://qiita.com/shun198/items/14cdba2d8e58ab96cf95

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
```
name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          # REDIS_URL: redis://localhost:6379/0
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
```

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
`run: bin/rails db:test:prepare test test:system`の部分を`run: bundle exec rspec`に変更できたら完了なのでしょうか。
